"""
Auto-generated action constants from player-action.schema.json

DO NOT EDIT MANUALLY - Run: python3 scripts/generate_actions.py
"""

ACTION_ACTIVATE_TACTIC = "ACTIVATE_TACTIC"
ACTION_ACTIVATE_UNIT = "ACTIVATE_UNIT"
ACTION_ALTAR_TRIBUTE = "ALTAR_TRIBUTE"
ACTION_ANNOUNCE_END_OF_ROUND = "ANNOUNCE_END_OF_ROUND"
ACTION_ASSIGN_ATTACK = "ASSIGN_ATTACK"
ACTION_ASSIGN_BANNER = "ASSIGN_BANNER"
ACTION_ASSIGN_BLOCK = "ASSIGN_BLOCK"
ACTION_ASSIGN_DAMAGE = "ASSIGN_DAMAGE"
ACTION_BURN_MONASTERY = "BURN_MONASTERY"
ACTION_BUY_HEALING = "BUY_HEALING"
ACTION_BUY_SPELL = "BUY_SPELL"
ACTION_CANCEL_COOPERATIVE_PROPOSAL = "CANCEL_COOPERATIVE_PROPOSAL"
ACTION_CHALLENGE_RAMPAGING = "CHALLENGE_RAMPAGING"
ACTION_CHOOSE_LEVEL_UP_REWARDS = "CHOOSE_LEVEL_UP_REWARDS"
ACTION_COMPLETE_REST = "COMPLETE_REST"
ACTION_CONVERT_INFLUENCE_TO_BLOCK = "CONVERT_INFLUENCE_TO_BLOCK"
ACTION_CONVERT_MOVE_TO_ATTACK = "CONVERT_MOVE_TO_ATTACK"
ACTION_DEBUG_ADD_FAME = "DEBUG_ADD_FAME"
ACTION_DEBUG_TRIGGER_LEVEL_UP = "DEBUG_TRIGGER_LEVEL_UP"
ACTION_DECLARE_ATTACK = "DECLARE_ATTACK"
ACTION_DECLARE_ATTACK_TARGETS = "DECLARE_ATTACK_TARGETS"
ACTION_DECLARE_BLOCK = "DECLARE_BLOCK"
ACTION_DECLARE_REST = "DECLARE_REST"
ACTION_DECLINE_PLUNDER = "DECLINE_PLUNDER"
ACTION_DISBAND_UNIT = "DISBAND_UNIT"
ACTION_END_COMBAT_PHASE = "END_COMBAT_PHASE"
ACTION_END_TURN = "END_TURN"
ACTION_ENTER_COMBAT = "ENTER_COMBAT"
ACTION_ENTER_SITE = "ENTER_SITE"
ACTION_EXPLORE = "EXPLORE"
ACTION_FINALIZE_ATTACK = "FINALIZE_ATTACK"
ACTION_INTERACT = "INTERACT"
ACTION_LEARN_ADVANCED = "LEARN_ADVANCED"
ACTION_MOVE = "MOVE"
ACTION_PAY_HEROES_ASSAULT_INFLUENCE = "PAY_HEROES_ASSAULT_INFLUENCE"
ACTION_PAY_THUGS_DAMAGE_INFLUENCE = "PAY_THUGS_DAMAGE_INFLUENCE"
ACTION_PLAY_CARD = "PLAY_CARD"
ACTION_PLAY_CARD_SIDEWAYS = "PLAY_CARD_SIDEWAYS"
ACTION_PLUNDER_VILLAGE = "PLUNDER_VILLAGE"
ACTION_PROPOSE_COOPERATIVE_ASSAULT = "PROPOSE_COOPERATIVE_ASSAULT"
ACTION_RECRUIT_UNIT = "RECRUIT_UNIT"
ACTION_REROLL_SOURCE_DICE = "REROLL_SOURCE_DICE"
ACTION_RESOLVE_ARTIFACT_CRYSTAL_COLOR = "RESOLVE_ARTIFACT_CRYSTAL_COLOR"
ACTION_RESOLVE_BANNER_PROTECTION = "RESOLVE_BANNER_PROTECTION"
ACTION_RESOLVE_BOOK_OF_WISDOM = "RESOLVE_BOOK_OF_WISDOM"
ACTION_RESOLVE_CHOICE = "RESOLVE_CHOICE"
ACTION_RESOLVE_CRYSTAL_JOY_RECLAIM = "RESOLVE_CRYSTAL_JOY_RECLAIM"
ACTION_RESOLVE_DECOMPOSE = "RESOLVE_DECOMPOSE"
ACTION_RESOLVE_DEEP_MINE = "RESOLVE_DEEP_MINE"
ACTION_RESOLVE_DISCARD = "RESOLVE_DISCARD"
ACTION_RESOLVE_DISCARD_FOR_ATTACK = "RESOLVE_DISCARD_FOR_ATTACK"
ACTION_RESOLVE_DISCARD_FOR_BONUS = "RESOLVE_DISCARD_FOR_BONUS"
ACTION_RESOLVE_DISCARD_FOR_CRYSTAL = "RESOLVE_DISCARD_FOR_CRYSTAL"
ACTION_RESOLVE_GLADE_WOUND = "RESOLVE_GLADE_WOUND"
ACTION_RESOLVE_HEX_COST_REDUCTION = "RESOLVE_HEX_COST_REDUCTION"
ACTION_RESOLVE_MAXIMAL_EFFECT = "RESOLVE_MAXIMAL_EFFECT"
ACTION_RESOLVE_MEDITATION = "RESOLVE_MEDITATION"
ACTION_RESOLVE_SOURCE_OPENING_REROLL = "RESOLVE_SOURCE_OPENING_REROLL"
ACTION_RESOLVE_STEADY_TEMPO = "RESOLVE_STEADY_TEMPO"
ACTION_RESOLVE_TACTIC_DECISION = "RESOLVE_TACTIC_DECISION"
ACTION_RESOLVE_TERRAIN_COST_REDUCTION = "RESOLVE_TERRAIN_COST_REDUCTION"
ACTION_RESOLVE_TRAINING = "RESOLVE_TRAINING"
ACTION_RESOLVE_UNIT_MAINTENANCE = "RESOLVE_UNIT_MAINTENANCE"
ACTION_RESPOND_TO_COOPERATIVE_PROPOSAL = "RESPOND_TO_COOPERATIVE_PROPOSAL"
ACTION_REST = "REST"
ACTION_RETURN_INTERACTIVE_SKILL = "RETURN_INTERACTIVE_SKILL"
ACTION_SELECT_REWARD = "SELECT_REWARD"
ACTION_SELECT_TACTIC = "SELECT_TACTIC"
ACTION_SPEND_MOVE_ON_CUMBERSOME = "SPEND_MOVE_ON_CUMBERSOME"
ACTION_UNASSIGN_ATTACK = "UNASSIGN_ATTACK"
ACTION_UNASSIGN_BLOCK = "UNASSIGN_BLOCK"
ACTION_UNDO = "UNDO"
ACTION_USE_BANNER_FEAR = "USE_BANNER_FEAR"
ACTION_USE_SKILL = "USE_SKILL"


ALL_ACTIONS = [
    ACTION_ACTIVATE_TACTIC,
    ACTION_ACTIVATE_UNIT,
    ACTION_ALTAR_TRIBUTE,
    ACTION_ANNOUNCE_END_OF_ROUND,
    ACTION_ASSIGN_ATTACK,
    ACTION_ASSIGN_BANNER,
    ACTION_ASSIGN_BLOCK,
    ACTION_ASSIGN_DAMAGE,
    ACTION_BURN_MONASTERY,
    ACTION_BUY_HEALING,
    ACTION_BUY_SPELL,
    ACTION_CANCEL_COOPERATIVE_PROPOSAL,
    ACTION_CHALLENGE_RAMPAGING,
    ACTION_CHOOSE_LEVEL_UP_REWARDS,
    ACTION_COMPLETE_REST,
    ACTION_CONVERT_INFLUENCE_TO_BLOCK,
    ACTION_CONVERT_MOVE_TO_ATTACK,
    ACTION_DEBUG_ADD_FAME,
    ACTION_DEBUG_TRIGGER_LEVEL_UP,
    ACTION_DECLARE_ATTACK,
    ACTION_DECLARE_ATTACK_TARGETS,
    ACTION_DECLARE_BLOCK,
    ACTION_DECLARE_REST,
    ACTION_DECLINE_PLUNDER,
    ACTION_DISBAND_UNIT,
    ACTION_END_COMBAT_PHASE,
    ACTION_END_TURN,
    ACTION_ENTER_COMBAT,
    ACTION_ENTER_SITE,
    ACTION_EXPLORE,
    ACTION_FINALIZE_ATTACK,
    ACTION_INTERACT,
    ACTION_LEARN_ADVANCED,
    ACTION_MOVE,
    ACTION_PAY_HEROES_ASSAULT_INFLUENCE,
    ACTION_PAY_THUGS_DAMAGE_INFLUENCE,
    ACTION_PLAY_CARD,
    ACTION_PLAY_CARD_SIDEWAYS,
    ACTION_PLUNDER_VILLAGE,
    ACTION_PROPOSE_COOPERATIVE_ASSAULT,
    ACTION_RECRUIT_UNIT,
    ACTION_REROLL_SOURCE_DICE,
    ACTION_RESOLVE_ARTIFACT_CRYSTAL_COLOR,
    ACTION_RESOLVE_BANNER_PROTECTION,
    ACTION_RESOLVE_BOOK_OF_WISDOM,
    ACTION_RESOLVE_CHOICE,
    ACTION_RESOLVE_CRYSTAL_JOY_RECLAIM,
    ACTION_RESOLVE_DECOMPOSE,
    ACTION_RESOLVE_DEEP_MINE,
    ACTION_RESOLVE_DISCARD,
    ACTION_RESOLVE_DISCARD_FOR_ATTACK,
    ACTION_RESOLVE_DISCARD_FOR_BONUS,
    ACTION_RESOLVE_DISCARD_FOR_CRYSTAL,
    ACTION_RESOLVE_GLADE_WOUND,
    ACTION_RESOLVE_HEX_COST_REDUCTION,
    ACTION_RESOLVE_MAXIMAL_EFFECT,
    ACTION_RESOLVE_MEDITATION,
    ACTION_RESOLVE_SOURCE_OPENING_REROLL,
    ACTION_RESOLVE_STEADY_TEMPO,
    ACTION_RESOLVE_TACTIC_DECISION,
    ACTION_RESOLVE_TERRAIN_COST_REDUCTION,
    ACTION_RESOLVE_TRAINING,
    ACTION_RESOLVE_UNIT_MAINTENANCE,
    ACTION_RESPOND_TO_COOPERATIVE_PROPOSAL,
    ACTION_REST,
    ACTION_RETURN_INTERACTIVE_SKILL,
    ACTION_SELECT_REWARD,
    ACTION_SELECT_TACTIC,
    ACTION_SPEND_MOVE_ON_CUMBERSOME,
    ACTION_UNASSIGN_ATTACK,
    ACTION_UNASSIGN_BLOCK,
    ACTION_UNDO,
    ACTION_USE_BANNER_FEAR,
    ACTION_USE_SKILL,
]
